// KAIDLY platform administration is used only by the KAIDLY team, so its interface is
// Estonian-only (a documented exception to the ET/EN/RU rule — docs/ARCHITECTURE.md).
// Customer-facing screens never use these strings.

export const ADMIN = {
  brand: "KAIDLY Admin",
  menuEntry: "KAIDLY Admin",
  backToApp: "Tagasi rakendusse",
  nav: {
    overview: "Ülevaade",
    users: "Kasutajad",
    companies: "Ettevõtted",
    deadlines: "Tähtajad",
    system: "Süsteem",
    audit: "Admini logi",
  },
  notice: "Platvormi haldus. Näed tugiteenuse metaandmeid, mitte klientide dokumente ega sissekannete sisu. Iga muudatus logitakse.",
  overview: {
    title: "Mis toimub KAIDLYs?",
    users: "Kasutajaid",
    usersActive: "Sisse loginud viimase 30 päeva jooksul",
    companies: "Ettevõtteid",
    companiesActive: "Aktiivseid",
    companiesDeactivated: "Deaktiveeritud",
    sites: "Objekte",
    installations: "Elektripaigaldisi",
    overdue: "Tähtaja ületanud tegevusi",
    dueSoon: "Tegevusi järgmise 14 päeva jooksul",
    deficienciesOpen: "Avatud puudusi",
    deficienciesSerious: "Neist kõrge või kriitiline",
    documents: "Dokumente",
    storage: "Failide maht",
    entries30d: "Sissekandeid viimase 30 päeva jooksul",
    activeOnly: "Tähtajad ja puudused arvestavad ainult aktiivseid ettevõtteid.",
  },
  users: {
    title: "Kasutajad",
    search: "Otsi nime, e-posti või ettevõtte järgi",
    searchButton: "Otsi",
    total: (n: number) => `${n} kasutajat`,
    name: "Nimi",
    email: "E-post",
    companies: "Ettevõtted",
    created: "Loodud",
    lastSignIn: "Viimati sisse loginud",
    never: "Pole sisse loginud",
    disabled: "Konto peatatud",
    unconfirmed: "E-post kinnitamata",
    platformAdmin: "Platvormi admin",
    none: "Kasutajaid ei leitud.",
    noName: "Nimi lisamata",
  },
  user: {
    account: "Konto",
    id: "Kasutaja ID",
    phone: "Telefon",
    language: "Keel",
    status: "Olek",
    active: "Aktiivne",
    memberships: "Ettevõtted ja rollid",
    noMemberships: "Ei kuulu ühessegi ettevõttesse.",
    usage: "Kasutus",
    usageEntries: "Sissekandeid",
    usageCompleted: "Tehtuks märgitud tegevusi",
    usageDeficiencies: "Lisatud puudusi",
    usageResolved: "Lahendatud puudusi",
    usageDocuments: "Üles laaditud dokumente",
    recent: "Viimased muudatused",
    recentNone: "Muudatusi pole.",
    recentHint: "Ainult muudatuse liik, ettevõte ja aeg — mitte sisu.",
    actions: "Toimingud",
    changeRole: "Muuda rolli",
    removeMember: "Eemalda ettevõttest",
    resetPassword: "Saada parooli taastamise link",
    resetPasswordBody: (email: string) =>
      `Kasutajale saadetakse tavaline parooli taastamise e-kiri aadressile ${email}. Parooli ei näe ega määra keegi peale kasutaja.`,
    resetSent: "Parooli taastamise link on saadetud.",
    disable: "Peata konto",
    disableBody: "Kasutaja ei saa enam sisse logida ja tema sisselogimised tühistatakse; juba avatud seadmetes lõpeb ligipääs hiljemalt tunni jooksul. Andmed ja liikmesused jäävad alles.",
    enable: "Taasta konto",
    enableBody: "Kasutaja saab taas sisse logida.",
    revokeSessions: "Lõpeta kõik sisselogimised",
    revokeBody: "Kasutaja sisselogimised tühistatakse kõigis seadmetes; juba avatud seadmetes lõpeb ligipääs hiljemalt tunni jooksul. Konto jääb aktiivseks.",
    done: "Tehtud.",
    self: "Oma kontot ei saa siit peatada.",
    noImpersonation: "Kasutajana sisse logida ega tema parooli vaadata ei saa — see on teadlik piirang.",
  },
  companies: {
    title: "Ettevõtted",
    search: "Otsi nime või registrikoodi järgi",
    total: (n: number) => `${n} ettevõtet`,
    name: "Ettevõte",
    owners: "Omanikud",
    members: "Liikmeid",
    sites: "Objekte",
    installations: "Paigaldisi",
    overdue: "Üle tähtaja",
    openDeficiencies: "Avatud puudusi",
    documents: "Dokumente",
    deactivated: "Deaktiveeritud",
    none: "Ettevõtteid ei leitud.",
  },
  company: {
    details: "Andmed",
    registryCode: "Registrikood",
    contactEmail: "Kontakt-e-post",
    contactPhone: "Kontakttelefon",
    address: "Aadress",
    slug: "Aadress lingis",
    created: "Loodud",
    status: "Olek",
    active: "Aktiivne",
    members: "Liikmed",
    counts: "Arvud",
    logEntries: "Sissekandeid",
    activities: "Aktiivseid tegevusi",
    dueSoon: "14 päeva jooksul",
    serious: "Kõrge/kriitiline puudus",
    storage: "Failide maht",
    recent: "Viimased muudatused",
    deadlinesLink: "Vaata ettevõtte tähtaegu",
    contentNote: "Dokumentide ja sissekannete sisu siin ei kuvata.",
  },
  deadlines: {
    title: "Tähtajad",
    intro:
      "Tähtaja ületanud ja järgmise 14 päeva tegevused ning avatud kõrge ja kriitilise raskusega puudused kõigis ettevõtetes. Ainult klientide endi sisestatud tähtajad — KAIDLY ei lisa õigusaktidest tähtaegu.",
    company: "Ettevõte",
    allCompanies: "Kõik ettevõtted",
    kind: "Liik",
    allKinds: "Kõik",
    activity: "Tegevus",
    deficiency: "Puudus",
    severity: "Raskus",
    allSeverities: "Kõrge ja kriitiline",
    high: "Kõrge",
    critical: "Kriitiline",
    state: "Seis",
    allStates: "Kõik",
    overdue: "Üle tähtaja",
    soon: "Peagi",
    open: "Avatud",
    from: "Alates",
    to: "Kuni",
    includeDeactivated: "Näita ka deaktiveeritud ettevõtteid",
    apply: "Rakenda",
    reset: "Tühista filtrid",
    item: "Tegevus / puudus",
    where: "Objekt · paigaldis",
    due: "Tähtaeg",
    responsible: "Vastutaja",
    noDue: "Tähtaeg puudub",
    none: "Selliseid tähtaegu pole.",
    count: (n: number) => `${n} rida`,
    site: "Objekt",
    allSites: "Kõik objektid",
  },
  system: {
    title: "Süsteem",
    environment: "Keskkond",
    commit: "Versioon (commit)",
    branch: "Haru",
    latestMigration: "Viimane migratsioon",
    migrations: "Rakendatud migratsioone",
    users: "Kasutajaid",
    companies: "Ettevõtteid",
    documents: "Dokumente",
    pendingUploads: "Lõpetamata üleslaadimisi",
    storage: "Failide maht",
    admins: "Platvormi admineid",
    blockers: "Enne avalikku käivitamist",
    blockerItems: [
      "Üleslaadimiste kvoot ja päringute piiramine (rate limiting).",
      "Andmete säilitamise reeglid (õiguslik säilitamisaeg) kinnitamata.",
      "Isikuandmete kustutamise (privacy erasure) lahendus kavandamata.",
      "Venekeelse terminoloogia ülevaatus elektrivaldkonna spetsialisti poolt.",
      "Eestikeelse elektrivaldkonna sõnastuse ülevaatus.",
    ],
    unknown: "Pole teada",
  },
  audit: {
    title: "Admini logi",
    intro: "Kõik platvormi admini muudatused. Logi ei sisalda paroole, võtmeid ega klientide sisu.",
    when: "Aeg",
    admin: "Admin",
    action: "Toiming",
    target: "Sihtmärk",
    none: "Logi on tühi.",
    system: "Süsteem",
    actions: {
      platform_admin_granted: "Platvormi admini õigus antud",
      membership_role_changed: "Roll muudetud",
      membership_removed: "Liige eemaldatud",
      account_disabled: "Konto peatatud",
      account_enabled: "Konto taastatud",
      sessions_revoked: "Sisselogimised lõpetatud",
      password_reset_requested: "Parooli taastamise link saadetud",
    } as Record<string, string>,
  },
  confirm: {
    cancel: "Loobu",
    confirm: "Kinnita",
    typeToConfirm: (word: string) => `Kinnitamiseks kirjuta: ${word}`,
  },
  roles: { owner: "Omanik", admin: "Administraator", operator: "Käitaja", viewer: "Vaataja" } as Record<string, string>,
  errors: {
    not_found: "Seda ei leitud.",
    last_owner: "Ettevõttel peab jääma vähemalt üks omanik.",
    forbidden: "Seda ei saa teha.",
    confirmation: "Kinnitus ei vasta.",
    unknown: "Midagi läks valesti. Proovi uuesti.",
  },
  table: {
    actions: "Toimingud",
    open: "Ava",
    previous: "Eelmised",
    next: "Järgmised",
  },
  history: {
    insert: "lisati",
    update: "muudeti",
    delete: "kustutati",
    tables: {
      organisations: "Ettevõte",
      organisation_members: "Liige",
      organisation_invitations: "Kutse",
      sites: "Objekt",
      electrical_installations: "Paigaldis",
      log_entries: "Sissekanne",
      scheduled_activities: "Tegevus",
      deficiencies: "Puudus",
      documents: "Dokument",
    } as Record<string, string>,
  },
} as const;

export type AdminErrorKey = keyof typeof ADMIN.errors;
