import { ADMIN_MENU_ENTRY } from "./brand";

// KAIDLY platform administration is used only by the KAIDLY team, so its interface is
// Estonian-only (a documented exception to the ET/EN/RU rule — docs/ARCHITECTURE.md).
// Customer-facing screens never use these strings.

export const ADMIN = {
  brand: "KAIDLY Admin",
  menuEntry: ADMIN_MENU_ENTRY,
  backToApp: "Tagasi rakendusse",
  nav: {
    overview: "Ülevaade",
    users: "Kasutajad",
    companies: "Ettevõtted",
    subscriptions: "Tellimused",
    deadlines: "Tähtajad",
    system: "Süsteem",
    audit: "Admini logi",
  },
  notice: "Platvormi haldus. Näed tugiteenuse metaandmeid, mitte klientide dokumente ega sissekannete sisu. Iga muudatus logitakse.",
  overview: {
    title: "Mis toimub KAIDLYs?",
    users: "Kasutajaid",
    usersActive: "Sisse loginud viimase 30 päeva jooksul",
    companies: "Ettevõtteid",
    companiesActive: "Aktiivseid",
    companiesDeactivated: "Deaktiveeritud",
    sites: "Objekte",
    installations: "Elektripaigaldisi",
    overdue: "Tähtaja ületanud tegevusi",
    dueSoon: "Tegevusi järgmise 14 päeva jooksul",
    deficienciesOpen: "Avatud puudusi",
    deficienciesSerious: "Neist kõrge või kriitiline",
    documents: "Dokumente",
    storage: "Failide maht",
    entries30d: "Sissekandeid viimase 30 päeva jooksul",
    activeOnly: "Tähtajad ja puudused arvestavad ainult aktiivseid ettevõtteid.",
  },
  users: {
    title: "Kasutajad",
    search: "Otsi nime, e-posti või ettevõtte järgi",
    searchButton: "Otsi",
    total: (n: number) => `${n} kasutajat`,
    name: "Nimi",
    email: "E-post",
    companies: "Ettevõtted",
    created: "Loodud",
    lastSignIn: "Viimati sisse loginud",
    never: "Pole sisse loginud",
    disabled: "Konto peatatud",
    unconfirmed: "E-post kinnitamata",
    platformAdmin: "Platvormi admin",
    none: "Kasutajaid ei leitud.",
    noName: "Nimi lisamata",
  },
  user: {
    account: "Konto",
    id: "Kasutaja ID",
    phone: "Telefon",
    language: "Keel",
    status: "Olek",
    active: "Aktiivne",
    memberships: "Ettevõtted ja rollid",
    noMemberships: "Ei kuulu ühessegi ettevõttesse.",
    usage: "Kasutus",
    usageEntries: "Sissekandeid",
    usageCompleted: "Tehtuks märgitud tegevusi",
    usageDeficiencies: "Lisatud puudusi",
    usageResolved: "Lahendatud puudusi",
    usageDocuments: "Üles laaditud dokumente",
    recent: "Viimased muudatused",
    recentNone: "Muudatusi pole.",
    recentHint: "Ainult muudatuse liik, ettevõte ja aeg — mitte sisu.",
    actions: "Toimingud",
    changeRole: "Muuda rolli",
    removeMember: "Eemalda ettevõttest",
    resetPassword: "Saada parooli taastamise link",
    resetPasswordBody: (email: string) =>
      `Kasutajale saadetakse tavaline parooli taastamise e-kiri aadressile ${email}. Parooli ei näe ega määra keegi peale kasutaja.`,
    resetSent: "Parooli taastamise link on saadetud.",
    disable: "Peata konto",
    disableBody: "Kasutaja ei saa enam sisse logida ja tema sisselogimised tühistatakse; juba avatud seadmetes lõpeb ligipääs hiljemalt tunni jooksul. Andmed ja liikmesused jäävad alles.",
    enable: "Taasta konto",
    enableBody: "Kasutaja saab taas sisse logida.",
    revokeSessions: "Lõpeta kõik sisselogimised",
    revokeBody: "Kasutaja sisselogimised tühistatakse kõigis seadmetes; juba avatud seadmetes lõpeb ligipääs hiljemalt tunni jooksul. Konto jääb aktiivseks.",
    done: "Tehtud.",
    self: "Oma kontot ei saa siit peatada.",
    noImpersonation: "Kasutajana sisse logida ega tema parooli vaadata ei saa — see on teadlik piirang.",
  },
  companies: {
    title: "Ettevõtted",
    search: "Otsi nime või registrikoodi järgi",
    total: (n: number) => `${n} ettevõtet`,
    name: "Ettevõte",
    owners: "Omanikud",
    members: "Liikmeid",
    sites: "Objekte",
    installations: "Paigaldisi",
    overdue: "Üle tähtaja",
    openDeficiencies: "Avatud puudusi",
    documents: "Dokumente",
    deactivated: "Deaktiveeritud",
    none: "Ettevõtteid ei leitud.",
  },
  company: {
    details: "Andmed",
    registryCode: "Registrikood",
    contactEmail: "Kontakt-e-post",
    contactPhone: "Kontakttelefon",
    address: "Aadress",
    slug: "Aadress lingis",
    created: "Loodud",
    status: "Olek",
    active: "Aktiivne",
    members: "Liikmed",
    counts: "Arvud",
    logEntries: "Sissekandeid",
    activities: "Aktiivseid tegevusi",
    dueSoon: "14 päeva jooksul",
    serious: "Kõrge/kriitiline puudus",
    storage: "Failide maht",
    recent: "Viimased muudatused",
    deadlinesLink: "Vaata ettevõtte tähtaegu",
    contentNote: "Dokumentide ja sissekannete sisu siin ei kuvata.",
  },
  deadlines: {
    title: "Tähtajad",
    intro:
      "Tähtaja ületanud ja järgmise 14 päeva tegevused ning avatud kõrge ja kriitilise raskusega puudused kõigis ettevõtetes. Ainult klientide endi sisestatud tähtajad — KAIDLY ei lisa õigusaktidest tähtaegu.",
    company: "Ettevõte",
    allCompanies: "Kõik ettevõtted",
    kind: "Liik",
    allKinds: "Kõik",
    activity: "Tegevus",
    deficiency: "Puudus",
    severity: "Raskus",
    allSeverities: "Kõrge ja kriitiline",
    high: "Kõrge",
    critical: "Kriitiline",
    state: "Seis",
    allStates: "Kõik",
    overdue: "Üle tähtaja",
    soon: "Peagi",
    open: "Avatud",
    from: "Alates",
    to: "Kuni",
    includeDeactivated: "Näita ka deaktiveeritud ettevõtteid",
    apply: "Rakenda",
    reset: "Tühista filtrid",
    item: "Tegevus / puudus",
    where: "Objekt · paigaldis",
    due: "Tähtaeg",
    responsible: "Vastutaja",
    noDue: "Tähtaeg puudub",
    none: "Selliseid tähtaegu pole.",
    count: (n: number) => `${n} rida`,
    capped: (shown: number, total: number) =>
      `Näidatakse ${shown} kõige pakilisemat ${total}-st. Kitsenda ettevõtte, liigi, seisu või kuupäevaga.`,
    site: "Objekt",
    allSites: "Kõik objektid",
  },
  system: {
    title: "Süsteem",
    environment: "Keskkond",
    commit: "Versioon (commit)",
    branch: "Haru",
    latestMigration: "Viimane migratsioon",
    migrations: "Rakendatud migratsioone",
    users: "Kasutajaid",
    companies: "Ettevõtteid",
    documents: "Dokumente",
    pendingUploads: "Lõpetamata üleslaadimisi",
    storage: "Failide maht",
    admins: "Platvormi admineid",
    blockers: "Enne avalikku käivitamist",
    blockerItems: [
      "Tootmiskeskkonna Supabase projekt (varundusega plaan) ja Vercel Production keskkonnamuutujad.",
      "Oma SMTP ja saatja domeen (no-reply@kaidly.ee) ning kontaktpostkast.",
      "Teenuse osutaja andmed privaatsus- ja kasutustingimuste lehtedele ning õiguslik ülevaatus.",
      "Andmete säilitamise reeglid (õiguslik säilitamisaeg) kinnitamata; isikuandmete kustutamine on käsitsi protsess.",
      "Dokumendifailide (Storage) varukoopia lahendus.",
      "Venekeelse terminoloogia ja eestikeelse elektrivaldkonna sõnastuse ülevaatus.",
    ],
    unknown: "Pole teada",
  },
  audit: {
    title: "Admini logi",
    intro: "Kõik platvormi admini muudatused. Logi ei sisalda paroole, võtmeid ega klientide sisu.",
    when: "Aeg",
    admin: "Admin",
    action: "Toiming",
    target: "Sihtmärk",
    none: "Logi on tühi.",
    system: "Süsteem",
    actions: {
      platform_admin_granted: "Platvormi admini õigus antud",
      membership_role_changed: "Roll muudetud",
      membership_removed: "Liige eemaldatud",
      account_disabled: "Konto peatatud",
      account_enabled: "Konto taastatud",
      sessions_revoked: "Sisselogimised lõpetatud",
      password_reset_requested: "Parooli taastamise link saadetud",
      trial_extended: "Prooviperioodi pikendati",
      full_access_set: "Täiskasutus aktiveeriti / muudeti",
      subscription_set: "Tellimus muudeti",
      access_expired: "Ligipääs lõpetati",
      access_reference_changed: "Arve viide / märkmed muudeti",
    } as Record<string, string>,
  },
  confirm: {
    cancel: "Loobu",
    confirm: "Kinnita",
    typeToConfirm: (word: string) => `Kinnitamiseks kirjuta: ${word}`,
  },
  roles: { owner: "Omanik", admin: "Administraator", operator: "Käitaja", viewer: "Vaataja" } as Record<string, string>,
  errors: {
    not_found: "Seda ei leitud.",
    last_owner: "Ettevõttel peab jääma vähemalt üks omanik.",
    forbidden: "Seda ei saa teha.",
    confirmation: "Kinnitus ei vasta.",
    invalid_date: "Kuupäev peab olema tulevikus (ja pikendus praegusest lõpust hilisem).",
    invalid_subscription:
      "Kontrolli väärtusi: Custom paketil on nimi, hind ja limiidid; makstud-kuni kuupäev ei ole minevikus; korraga kas kuud või kuupäev.",
    stale: "Andmed muutusid vahepeal — vaata kokkuvõte uuesti üle.",
    unknown: "Midagi läks valesti. Proovi uuesti.",
  },
  subs: {
    title: "Tellimused",
    intro: "Kõigi ettevõtete paketid, kehtivus ja kasutus. Pakette ja makstud perioode muudab ainult platvormi admin; iga muudatus logitakse.",
    search: "Otsi ettevõtet või Custom paketi nime",
    searchSubmit: "Otsi",
    filter: "Filter",
    filters: {
      all: "Kõik",
      trial: "Prooviperiood",
      active: "Aktiivne",
      expired: "Aegunud",
      deactivated: "Deaktiveeritud",
      ending_soon: "Lõpeb 14 päeva jooksul",
      no_plan: "Paketita",
      start: "Start",
      team: "Team",
      pro: "Pro",
      business: "Business",
      custom: "Custom",
    } as Record<string, string>,
    count: (n: number) => (n === 1 ? "1 ettevõte" : `${n} ettevõtet`),
    empty: "Ühtegi ettevõtet ei leitud.",
    company: "Ettevõte",
    plan: "Pakett",
    status: "Olek",
    trialEnd: "Prooviperiood kuni",
    paidUntil: "Makstud kuni",
    users: "Kasutajad",
    installations: "Paigaldised",
    manage: "Halda",
    noPlan: "Paketita",
    indefinite: "Tähtajatu",
    usage: (used: number, limit: number | null) => (limit === null ? `${used} / –` : `${used} / ${limit}`),
    current: "Praegune tellimus",
    monthly: "Kuutasu",
    price: (p: number | string) => `${p} € / kuu + KM`,
    start: "Tellimuse algus",
    change: "Muuda tellimust",
    changeIntro:
      "Fikseeritud paketi hind ja limiidid tulevad paketist. Custom paketi väärtused sisestad ise. Enne salvestamist näed kokkuvõtet ja kinnitad selle.",
    planField: "Pakett",
    customLabel: "Custom paketi nimi",
    customPrice: "Kokkulepitud kuutasu (€, ilma KM-ta)",
    userLimit: "Kasutajate limiit (kokku)",
    installationLimit: "Aktiivsete elektripaigaldiste limiit",
    fixedValues: (p: { price: number; users: number; installations: number }) =>
      `${p.price} € / kuu + KM · kasutajaid ${p.users} · aktiivseid paigaldisi ${p.installations}`,
    period: "Periood",
    periods: {
      none: "Kehtivust ei muuda (ainult pakett / limiidid)",
      "1": "1 kuu",
      "3": "3 kuud",
      "6": "6 kuud",
      "12": "12 kuud",
      "24": "24 kuud",
      date: "Kindla kuupäevani",
    } as Record<string, string>,
    periodHint:
      "Aktiivne tellimus pikeneb praegusest makstud-kuni kuupäevast. Prooviperioodil või aegunud ettevõttel algab periood alguskuupäevast (vaikimisi täna). Kuud arvestatakse kalendrikuudena; kuu viimane päev jääb kuu viimaseks päevaks.",
    paidUntilField: "Makstud kuni (kaasa arvatud)",
    startField: "Alguskuupäev",
    review: "Vaata üle",
    summary: "Kokkuvõte",
    modes: {
      activate: "Aktiveerimine",
      extend: "Pikendamine",
      set_until: "Kehtivuse muutmine",
      plan_only: "Paketi või limiitide muutmine",
    } as Record<string, string>,
    summaryUsers: (n: number) => `Kasutajad: ${n}`,
    summaryInstallations: (n: number) => `Paigaldised: ${n}`,
    summaryPeriod: (months: number) => `Periood: ${months === 1 ? "1 kuu" : `${months} kuud`}`,
    summaryFrom: (day: string) => `Algus: ${day}`,
    summaryUntil: (day: string) => `Kehtib kuni: ${day}`,
    summaryUnchanged: "Kehtivus ei muutu",
    overLimit: (what: string, used: number, limit: number) =>
      `${what}: praegu ${used}, uus limiit ${limit}. Olemasolevad jäävad alles; uusi lisada ei saa enne, kui ollakse limiidi all.`,
    applyTitle: "Kinnita muudatus",
    applyBody: "Muudatus mõjutab kliendi ligipääsu või limiite kohe. Kontrolli kokkuvõtet.",
    apply: "Kinnita ja rakenda",
    edit: "Muuda",
    saved: "Tellimus salvestatud.",
    note: "Arve viide ja sisemine märkus",
    noteHint: "Märkust ja viidet näeb ainult platvormi admin, mitte klient.",
    trialTitle: "Prooviperiood ja ligipääsu lõpetamine",
    history: "Muudatuste ajalugu",
    historyAt: "Aeg",
    historyBy: "Muutja",
    historyWhat: "Muudatus",
    historyPlan: "Pakett",
    historyUntil: "Makstud kuni",
    historyLimits: "Limiidid (kasutajad / paigaldised)",
    historyEmpty: "Muudatusi pole veel.",
    arrow: (a: string, b: string) => (a === b ? a : `${a} → ${b}`),
    companyLink: "Halda tellimust",
    companyCard: "Ettevõtte kaart",
    back: "Tellimused",
  },
  table: {
    actions: "Toimingud",
    open: "Ava",
    previous: "Eelmised",
    next: "Järgmised",
  },
  access: {
    title: "KAIDLY ligipääs",
    status: "Olek",
    statuses: { trial: "Prooviperiood", active: "Täiskasutus", expired: "Aegunud", deactivated: "Deaktiveeritud" } as Record<string, string>,
    trialStart: "Prooviperioodi algus",
    trialEnd: "Prooviperioodi lõpp",
    fullFrom: "Täiskasutuse algus",
    until: "Ligipääs kuni",
    indefinite: "Tähtajatu",
    activatedBy: "Aktiveeris",
    invoice: "Arve / viide",
    notes: "Admini märkmed",
    expired90: "Aegunud 90+ päeva",
    expired90Body:
      "Ettevõte on olnud aegunud üle 90 päeva. Midagi ei kustutata automaatselt. Tühja ettevõtte võib omanik kustutada; käiduajalooga ettevõtet saab ainult deaktiveerida.",
    activate: "Aktiveeri täiskasutus",
    activateBody: "Täiskasutus algab kohe. Arvet KAIDLY ei koosta — viide on ainult märkmeks.",
    period: "Periood",
    periods: { "1": "1 kuu", "3": "3 kuud", "6": "6 kuud", "12": "12 kuud", indefinite: "Tähtajatu", custom: "Kuni kuupäevani" } as Record<string, string>,
    customDate: "Lõppkuupäev (kaasa arvatud)",
    extend: "Pikenda prooviperioodi",
    extendBody: "Pikendus arvestatakse praegusest lõpust (või tänasest, kui see on möödas). Algus jääb samaks.",
    extendOptions: { "7": "+7 päeva", "14": "+14 päeva", "30": "+30 päeva", custom: "Kuni kuupäevani" } as Record<string, string>,
    expire: "Lõpeta ligipääs",
    expireBody: "Ettevõte muutub kohe ainult vaatamiseks. Andmeid ei kustutata. Täiskasutuse saab hiljem taastada.",
    reference: "Muuda viidet ja märkmeid",
    save: "Salvesta",
    filters: { all: "Kõik", trial: "Prooviperiood", active: "Täiskasutus", expired: "Aegunud", deactivated: "Deaktiveeritud", ending_soon: "Lõpeb 7 päeva jooksul", expired_90: "Aegunud 90+ päeva" } as Record<string, string>,
    remaining: (days: number) => (days === 0 ? "Lõpeb täna" : days === 1 ? "1 päev jäänud" : `${days} päeva jäänud`),
    ago: (days: number) => (days === 0 ? "Lõppes täna" : days === 1 ? "1 päev tagasi lõppenud" : `${days} päeva tagasi lõppenud`),
    overview: {
      trials: "Aktiivseid prooviperioode",
      ending: "Prooviperiood lõpeb 7 päeva jooksul",
      expiredTrials: "Aegunud prooviperioode",
      active: "Täiskasutusega ettevõtteid",
      expired: "Aegunud ligipääsuga",
      expired90: "Aegunud 90+ päeva",
    },
    endsColumn: "Proov lõpeb / ligipääs kuni",
    created: "Loodud",
  },
  history: {
    insert: "lisati",
    update: "muudeti",
    delete: "kustutati",
    tables: {
      organisations: "Ettevõte",
      organisation_members: "Liige",
      organisation_invitations: "Kutse",
      sites: "Objekt",
      electrical_installations: "Paigaldis",
      log_entries: "Sissekanne",
      scheduled_activities: "Tegevus",
      deficiencies: "Puudus",
      documents: "Dokument",
    } as Record<string, string>,
  },
} as const;

export type AdminErrorKey = keyof typeof ADMIN.errors;
