#!/usr/bin/env bash
# KAIDLY — restore a database backup (docs/PRODUCTION_BACKUP_RECOVERY.md).
#
#   scripts/restore-database.sh <backup dir>            prepare <backup dir>/restore.sql only
#   scripts/restore-database.sh <backup dir> --local    rehearsal: rebuild the LOCAL stack from the
#                                                       migrations (no seed) and load the data
#
# Never restores into Production: it only ever writes to the local Docker database, and the
# prepared restore.sql refuses any database that already has user accounts. For a
# real recovery into a NEW Supabase project, the prepared restore.sql is loaded with psql as
# described in the recovery document.
#
# restore.sql = one transaction: triggers off for the session (session_replication_role =
# replica, so history/limits/reminders are not re-fired and foreign keys are not checked
# row by row), every table that the backup contains is emptied first (a fresh project only
# holds rows the migrations created, e.g. upload limits, e-mail templates), then the data is
# copied in. The storage schema is skipped: the files are uploaded again by
# scripts/restore-storage.mjs, which recreates their rows with the same bucket and path.
set -euo pipefail

DIR="${1:?usage: restore-database.sh <backup dir> [--local]}"
MODE="${2:-prepare}"
[[ -f "$DIR/data.sql" ]] || { echo "No data.sql in $DIR" >&2; exit 1; }
REPO="$(cd "$(dirname "$0")/.." && pwd)"
CONTAINER="supabase_db_kaidly"
umask 077

if [[ -f "$DIR/SHA256SUMS" ]]; then
  ( cd "$DIR" && shasum -a 256 -c SHA256SUMS --quiet ) || { echo "Checksum mismatch in $DIR — refusing." >&2; exit 1; }
fi

# Tables in the backup, minus the storage schema: the bucket comes from the migrations,
# object rows are recreated by the file upload, and Storage's own tables belong to its role.
SKIP='^"storage"\.'
TABLES=$(grep -E '^COPY ' "$DIR/data.sql" | awk '{print $2}' | grep -vE "$SKIP")

{
  echo "-- KAIDLY restore of $(basename "$DIR") — generated by scripts/restore-database.sh"
  echo "\\set ON_ERROR_STOP on"
  echo "begin;"
  # Safety net for the manual psql step: a restore empties every table first, so it only
  # ever goes into a NEW project. A database that already has accounts (Production, or any
  # project in use) is refused before anything is touched.
  echo "do \$\$ begin if exists (select 1 from auth.users) then raise exception 'KAIDLY restore refused: the target database already has user accounts. Restore only into a NEW, empty project - never into Production.'; end if; end \$\$;"
  echo "set local session_replication_role = replica;"
  for t in $TABLES; do echo "delete from $t;"; done
  # The data, without the skipped COPY blocks (and without the dump's own SET lines for the session).
  awk -v skip="$SKIP" '
    /^COPY / { copying = 1; table = $2; drop = (table ~ skip); if (!drop) print; next }
    copying { if (!drop) print; if ($0 == "\\.") copying = 0; next }
    /^SET session_replication_role/ { next }
    /^(SET|SELECT pg_catalog\.set_config)/ { print; next }
    # Sequence positions (e.g. refresh tokens, audit log ids): without them new rows collide.
    /^SELECT pg_catalog\.setval/ { print; next }
  ' "$DIR/data.sql"
  echo "commit;"
} > "$DIR/restore.sql"
chmod 600 "$DIR/restore.sql"
echo "Prepared $DIR/restore.sql ($(echo "$TABLES" | wc -l | tr -d ' ') tables)."

[[ "$MODE" == "--local" ]] || exit 0

docker inspect "$CONTAINER" >/dev/null 2>&1 || { echo "Local stack is not running (npx supabase start)." >&2; exit 1; }
cd "$REPO"
echo "Rebuilding the LOCAL database from the migrations (no seed)…"
npx --no-install supabase db reset --no-seed >/dev/null 2>&1
# Every table in the backup must exist in the rebuilt schema (same or newer migrations).
missing=""
for t in $TABLES; do
  exists=$(docker exec -i "$CONTAINER" psql -U postgres -d postgres -qtA -c "select to_regclass('$t') is not null")
  [[ "$exists" == "t" ]] || missing="$missing $t"
done
if [[ -n "$missing" ]]; then
  echo "The backup has tables this schema lacks:$missing" >&2
  echo "Check out the commit in $DIR/meta.txt (or later) so the migrations match, then retry." >&2
  exit 1
fi
echo "Loading the data…"
docker exec -i "$CONTAINER" psql -U postgres -d postgres -q -v ON_ERROR_STOP=1 < "$DIR/restore.sql" >/dev/null
echo "Comparing row counts with the backup…"
fail=0
while IFS=$'\t' read -r table expected; do
  [[ "$table" =~ $SKIP ]] && continue
  actual=$(docker exec -i "$CONTAINER" psql -U postgres -d postgres -qtA -c "select count(*) from $table")
  if [[ "$actual" != "$expected" ]]; then echo "  MISMATCH $table: backup $expected, restored $actual"; fail=1; fi
done < "$DIR/counts.tsv"
[[ $fail -eq 0 ]] && echo "  all $(grep -cvE "$SKIP" "$DIR/counts.tsv") tables match." || exit 1
