-- KAIDLY Phase 7: documents and photos.
--
-- Files live in ONE private Storage bucket ("documents"); metadata lives here. Object paths
-- are generated by the database: <organisation_id>/<document_id>/<random uuid>. The user's
-- filename is metadata only and never part of the object key.
--
-- Upload lifecycle: a row is registered as `pending` → the browser uploads to exactly that
-- path → finalize_document() checks the object exists with the declared size and type →
-- `ready`. Only `ready` documents are listed or readable. An uploader may delete their own
-- pending/failed rows and objects (cleanup); nothing else is ever deleted.
--
-- History rules: documents attached to an operating-log entry or a deficiency are part of
-- the operational record — never archived, changed, replaced or deleted. New attachments
-- to a log entry are accepted only from its author within an hour of recording it (to
-- finish uploads); later material goes on a correction entry. General documents
-- (organisation, site, installation) may be archived by admins, never hard-deleted.

create type public.document_category as enum (
  'audit',                -- Audit
  'measurement_protocol', -- Mõõteprotokoll
  'single_line_diagram',  -- Ühejooneskeem
  'operating_plan',       -- Käidukava
  'maintenance_report',   -- Hooldusraport
  'declaration',          -- Deklaratsioon
  'manual',               -- Juhend
  'photo',                -- Foto
  'other'                 -- Muu
);

create type public.document_status as enum ('pending', 'ready', 'failed');

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  organisation_id uuid not null references public.organisations (id) on delete restrict,
  site_id uuid,
  electrical_installation_id uuid,
  log_entry_id uuid,
  deficiency_id uuid,
  category public.document_category not null,
  title text not null check (char_length(title) between 1 and 200 and title = btrim(title)),
  -- Display only. No path separators or control characters.
  original_filename text not null
    check (char_length(original_filename) between 1 and 255 and original_filename !~ '[/\\[:cntrl:]]'),
  -- Set by the insert trigger; never chosen by the client.
  storage_path text not null default '' unique,
  -- Conservative allowlist, kept identical to the bucket's allowed_mime_types.
  mime_type text not null check (mime_type in (
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  )),
  size_bytes bigint not null check (size_bytes between 1 and 26214400),
  status public.document_status not null default 'pending',
  uploaded_by uuid not null default auth.uid(),
  uploaded_by_name text not null default '',
  created_at timestamptz not null default now(),
  ready_at timestamptz,
  archived_at timestamptz,

  check (storage_path ~ ('^' || organisation_id::text || '/' || id::text || '/[0-9a-f-]{36}$')),
  check ((status = 'ready') = (ready_at is not null)),
  -- An installation implies its site; entry/deficiency attachments imply their installation.
  check (electrical_installation_id is null or site_id is not null),
  check ((log_entry_id is null and deficiency_id is null) or electrical_installation_id is not null),
  check (num_nonnulls(log_entry_id, deficiency_id) <= 1),
  -- Historical attachments are never archived.
  check (archived_at is null or (log_entry_id is null and deficiency_id is null)),

  foreign key (site_id, organisation_id)
    references public.sites (id, organisation_id) on delete restrict,
  foreign key (electrical_installation_id, organisation_id)
    references public.electrical_installations (id, organisation_id) on delete restrict,
  foreign key (electrical_installation_id, site_id)
    references public.electrical_installations (id, site_id) on delete restrict,
  foreign key (log_entry_id, electrical_installation_id)
    references public.log_entries (id, electrical_installation_id) on delete restrict,
  foreign key (deficiency_id, electrical_installation_id)
    references public.deficiencies (id, electrical_installation_id) on delete restrict
);

create index documents_org_listing_idx
  on public.documents (organisation_id, created_at desc) where status = 'ready';
create index documents_installation_idx on public.documents (electrical_installation_id, created_at desc);
create index documents_installation_org_idx on public.documents (electrical_installation_id, organisation_id);
create index documents_installation_site_idx on public.documents (electrical_installation_id, site_id);
create index documents_site_idx on public.documents (site_id, organisation_id);
create index documents_log_entry_idx on public.documents (log_entry_id, electrical_installation_id);
create index documents_deficiency_idx on public.documents (deficiency_id, electrical_installation_id);
create index documents_uploader_pending_idx on public.documents (uploaded_by) where status <> 'ready';

comment on table public.documents is
  'Document metadata. File bytes live in the private "documents" bucket at storage_path.';

-- ---------------------------------------------------------------------------
-- Rules
-- ---------------------------------------------------------------------------

create function private.document_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_entry record;
begin
  if v_user is not null then
    new.uploaded_by := v_user;
  end if;
  if new.uploaded_by is null then
    raise exception 'document_without_uploader' using errcode = '23502';
  end if;
  select coalesce(nullif(btrim(p.full_name), ''), p.email, 'Tundmatu')
    into new.uploaded_by_name from public.profiles p where p.id = new.uploaded_by;
  new.uploaded_by_name := coalesce(new.uploaded_by_name, 'Tundmatu');

  -- Server-generated, collision-free object key.
  new.storage_path := new.organisation_id::text || '/' || new.id::text || '/' || gen_random_uuid()::text;
  new.created_at := now();
  -- Seed/maintenance without a session may insert ready rows; users always start pending.
  if v_user is not null then
    new.status := 'pending';
    new.ready_at := null;
    new.archived_at := null;
  end if;

  if new.electrical_installation_id is not null and exists (
    select 1 from public.electrical_installations
     where id = new.electrical_installation_id and archived_at is not null
  ) then
    raise exception 'installation_archived' using errcode = 'P0001';
  end if;

  if new.log_entry_id is not null and v_user is not null then
    select created_by, created_at into v_entry from public.log_entries where id = new.log_entry_id;
    if v_entry.created_by is distinct from v_user or v_entry.created_at < now() - interval '1 hour' then
      raise exception 'log_entry_attachment_closed' using errcode = 'P0001';
    end if;
  end if;

  if new.deficiency_id is not null and exists (
    select 1 from public.deficiencies where id = new.deficiency_id and status = 'resolved'
  ) then
    raise exception 'deficiency_resolved' using errcode = 'P0001';
  end if;

  return new;
end;
$$;

create trigger document_before_insert
  before insert on public.documents
  for each row execute function private.document_before_insert();

-- Only title, category and archive state of general documents may change; status only
-- moves forward through finalize_document(). Everything about historical attachments is fixed.
create function private.document_before_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.storage_path is distinct from old.storage_path
     or new.organisation_id is distinct from old.organisation_id
     or new.site_id is distinct from old.site_id
     or new.electrical_installation_id is distinct from old.electrical_installation_id
     or new.log_entry_id is distinct from old.log_entry_id
     or new.deficiency_id is distinct from old.deficiency_id
     or new.mime_type is distinct from old.mime_type
     or new.size_bytes is distinct from old.size_bytes
     or new.original_filename is distinct from old.original_filename
     or new.uploaded_by is distinct from old.uploaded_by then
    raise exception 'document_immutable' using errcode = 'P0001';
  end if;
  if (old.log_entry_id is not null or old.deficiency_id is not null)
     and old.status = 'ready'
     and (new.title is distinct from old.title
          or new.category is distinct from old.category
          or new.archived_at is distinct from old.archived_at
          or new.status is distinct from old.status) then
    raise exception 'document_immutable' using errcode = 'P0001';
  end if;
  if old.status = 'ready' and new.status <> 'ready' then
    raise exception 'document_immutable' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger document_before_update
  before update on public.documents
  for each row execute function private.document_before_update();

-- Only incomplete uploads may disappear (cleanup by their uploader).
create function private.document_before_delete()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.status = 'ready' then
    raise exception 'documents_are_kept' using errcode = 'P0001';
  end if;
  return old;
end;
$$;

create trigger document_before_delete
  before delete on public.documents
  for each row execute function private.document_before_delete();
create function private.documents_no_truncate()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'documents_are_kept' using errcode = 'P0001';
end;
$$;

create trigger documents_no_truncate
  before truncate on public.documents
  for each statement execute function private.documents_no_truncate();

create trigger prevent_organisation_change
  before update on public.documents
  for each row execute function private.prevent_organisation_change();
create trigger record_history
  after insert or update or delete on public.documents
  for each row execute function private.record_history();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.documents enable row level security;

create policy "members read documents" on public.documents
  for select to authenticated
  using (organisation_id in (select private.org_ids('viewer')));

-- Operators upload documents of an installation (incl. log entries and deficiencies);
-- organisation- and site-level documents are admin+.
create policy "operators upload operational documents" on public.documents
  for insert to authenticated
  with check (
    organisation_id in (select private.org_ids('operator'))
    and (electrical_installation_id is not null or organisation_id in (select private.org_ids('admin')))
  );

create policy "admins manage general documents" on public.documents
  for update to authenticated
  using (organisation_id in (select private.org_ids('admin')))
  with check (organisation_id in (select private.org_ids('admin')));

create policy "uploaders remove incomplete uploads" on public.documents
  for delete to authenticated
  using (
    organisation_id in (select private.org_ids('operator'))
    and uploaded_by = (select auth.uid())
    and status <> 'ready'
  );

grant select on table public.documents to authenticated;
grant insert (
  organisation_id, site_id, electrical_installation_id, log_entry_id, deficiency_id,
  category, title, original_filename, mime_type, size_bytes
) on table public.documents to authenticated;
grant update (title, category, archived_at) on table public.documents to authenticated;
grant delete on table public.documents to authenticated;

-- ---------------------------------------------------------------------------
-- RPC: finalize_document
-- ---------------------------------------------------------------------------

-- Marks the uploader's pending document ready once the object really exists at its path
-- with the declared size and type. Anything else → `failed` (never listed or readable).
create function public.finalize_document(p_document_id uuid)
returns public.document_status
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_doc public.documents%rowtype;
  v_object record;
  v_status public.document_status;
begin
  if v_user is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  select * into v_doc from public.documents where id = p_document_id for update;
  if not found
     or v_doc.uploaded_by is distinct from v_user
     or not private.has_org_role(v_doc.organisation_id, 'operator') then
    raise exception 'not_found' using errcode = 'P0002';
  end if;
  if v_doc.status = 'ready' then
    return 'ready';
  end if;

  select o.metadata into v_object
    from storage.objects o
   where o.bucket_id = 'documents' and o.name = v_doc.storage_path;

  if found
     and (v_object.metadata ->> 'size')::bigint = v_doc.size_bytes
     and lower(v_object.metadata ->> 'mimetype') = v_doc.mime_type then
    v_status := 'ready';
  else
    v_status := 'failed';
  end if;

  update public.documents
     set status = v_status, ready_at = case when v_status = 'ready' then now() end
   where id = v_doc.id;
  return v_status;
end;
$$;

grant execute on function public.finalize_document(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Storage: one private bucket and its policies
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'documents', 'documents', false, 26214400,
  array[
    'application/pdf', 'image/jpeg', 'image/png', 'image/webp',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]
);

-- Read: only objects of ready documents the caller can see (documents RLS applies inside).
create policy "kaidly documents: read ready files" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'documents'
    and exists (
      select 1 from public.documents d
       where d.storage_path = storage.objects.name and d.status = 'ready'
    )
  );

-- Upload: only to a path registered as the caller's own pending document. Paths can't be
-- forged (they come from documents.storage_path) and nothing can be overwritten (no
-- update policy; a second upload to an existing name fails).
create policy "kaidly documents: upload registered pending files" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'documents'
    and exists (
      select 1 from public.documents d
       where d.storage_path = storage.objects.name
         and d.status = 'pending'
         and d.uploaded_by = (select auth.uid())
    )
  );

-- Delete: only the caller's own incomplete uploads (cleanup). Ready files are never deleted.
create policy "kaidly documents: remove own incomplete uploads" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'documents'
    and exists (
      select 1 from public.documents d
       where d.storage_path = storage.objects.name
         and d.status <> 'ready'
         and d.uploaded_by = (select auth.uid())
    )
  );
