import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { isAllowedRedirectPath } from "../../lib/auth/redirect.ts";
import { appEmail, appTemplatesSql, configToml, LANGS, preview, TEMPLATES, templateHtml, templateSubject } from "../../scripts/email-templates.mjs";

// Supabase Auth / security e-mail templates (docs/EMAIL_TEMPLATES.md). The repo files are
// generated by scripts/email-templates.mjs and pasted into the Supabase dashboard.
type Template = { kind: "auth" | "notification"; active: boolean; cta?: { href: string }; code?: string };
const ALL = TEMPLATES as Record<string, Template>;
const repo = (file: string) => new URL(`../../${file}`, import.meta.url);
const read = (name: string) => readFileSync(repo(`supabase/templates/${name}.html`), "utf8");

const ROUTE_TYPES = ["signup", "invite", "magiclink", "recovery", "email_change", "email"]; // app/auth/confirm/route.ts
const LINKS: Record<string, { type: string; next: string }> = {
  confirmation: { type: "email", next: "/o" },
  recovery: { type: "recovery", next: "/auth/update-password" },
  email_change: { type: "email_change", next: "/konto" },
  invite: { type: "invite", next: "/auth/update-password" },
  magic_link: { type: "magiclink", next: "/o" },
};
const REQUIRED = [
  "confirmation", "recovery", "email_change", "invite", "magic_link", "reauthentication",
  "password_changed_notification", "email_changed_notification", "phone_changed_notification",
  "identity_linked_notification", "identity_unlinked_notification",
  "mfa_factor_enrolled_notification", "mfa_factor_unenrolled_notification",
];
// Account-level placeholders only: nothing about companies, sites, installations or the log.
const ALLOWED_VARS = new Set([".SiteURL", ".TokenHash", ".Token", ".NewEmail", ".Email", ".OldEmail", ".Provider", ".FactorType", ".Data", ".locale"]);

test("every required template exists and matches the generator", () => {
  assert.deepEqual(Object.keys(ALL).sort(), [...REQUIRED].sort());
  for (const name of REQUIRED) assert.equal(read(name), templateHtml(name), `${name}: run node scripts/email-templates.mjs`);
});

test("local config.toml wires the same files and subjects", () => {
  const config = readFileSync(repo("supabase/config.toml"), "utf8");
  assert.ok(config.includes(configToml()), "run node scripts/email-templates.mjs");
  // The app supports the reauthentication code step, so the local stack runs with it (the
  // E2E suite covers it); Production is switched on by hand after a real code test.
  assert.match(config, /secure_password_change = true/);
});

test("the old logo URL keeps working for templates pasted before the image-free header", () => {
  const png = readFileSync(repo("public/email/kaidly-mark.png"));
  assert.equal(png.subarray(1, 4).toString(), "PNG");
});

for (const name of REQUIRED) {
  test(`${name}: safe, branded, trilingual`, () => {
    const html = read(name);
    const subject = templateSubject(name);

    // Language: chosen only from metadata `locale` (en / ru), Estonian otherwise; never printed.
    const preamble = '{{ $l := "et" }}{{ with .Data }}{{ with .locale }}{{ $l = . }}{{ end }}{{ end }}';
    assert.ok(subject.startsWith(preamble) && html.includes(`-->\n${preamble}`));
    for (const text of [html, subject]) {
      assert.match(text, /\{\{ if eq \$l "en" \}\}[\s\S]*\{\{ else if eq \$l "ru" \}\}[\s\S]*\{\{ else \}\}[\s\S]*\{\{ end \}\}/);
      assert.doesNotMatch(text, /\{\{\s*(\$l|\.locale|\.Data)\s*\}\}/);
    }
    assert.match(html, /[õäöü]/, "Estonian");
    assert.match(html, /[а-яё]/i, "Russian");
    assert.match(html, /\b(your|you|the)\b/i, "English");

    // Only account-level placeholders.
    for (const [, variable] of html.matchAll(/\{\{[^}]*?(\.[A-Za-z]+)[^}]*\}\}/g)) assert.ok(ALLOWED_VARS.has(variable), `${name}: ${variable}`);
    assert.doesNotMatch(html, /\{\{\s*\.ConfirmationURL\s*\}\}/, "token_hash links to KAIDLY, not the Supabase verify URL");
    assert.doesNotMatch(html, /\{\{\s*\.Data\.[a-z]/i, "no free-form metadata printed");

    // No environment hosts, tracking or secrets; the only absolute host is kaidly.ee.
    assert.doesNotMatch(html, /localhost|127\.0\.0\.1|vercel\.app|supabase\.co|preview|gdpzavhkblbcxivoaqax|xakpbtmksxvjmsbipwmj/i);
    for (const [, url] of html.matchAll(/https?:\/\/([^/"'\s<>]+)/g)) assert.equal(url, "kaidly.ee");
    assert.doesNotMatch(html, /utm_|[?&](ref|src|cid|mc_[a-z]+)=|resend|click\.|track|pixel|unsubscribe/i);
    // Image-free: nothing can render as a broken image, and blocked images change nothing.
    assert.doesNotMatch(html, /<img\b|<svg\b|<picture\b|data:|background-image|url\(|\.png|\.svg|\.webp|\.gif|\.jpe?g/i);
    const header = /<td [^>]*bgcolor="#22D07A"[^>]*>&nbsp;<\/td>\s*<td [^>]*>&nbsp;<\/td>\s*<td [^>]*color:#0F3D32;">KAIDLY<\/td>/g;
    assert.equal(html.match(header)?.length, 3, "header: volt block + text wordmark, once per language");
    assert.doesNotMatch(html, /sb_secret_|sb_publishable_|service_role|eyJ[A-Za-z0-9_-]{20,}|password=|apikey/i);
    assert.doesNotMatch(html, /<script|<style|<link|@import|javascript:/i, "inline styles only");

    // Branding and footer (no company legal data).
    assert.equal(html.match(/>KAIDLY</g)?.length, 6, "text wordmark + footer, per language");
    assert.ok(html.includes("Elektripaigaldise käit. Lihtsalt."));
    assert.equal(html.match(/>kaidly\.ee</g)?.length, 3);
    assert.doesNotMatch(html, /OÜ|AS\b|registrikood|reg\. ?nr|VAT|KMKR/);

    // Layout: tables, max width, balanced markup.
    assert.match(html, /max-width:560px/);
    for (const tag of ["table", "tr", "td", "a", "p", "h1"]) {
      const open = html.match(new RegExp(`<${tag}[\\s>]`, "g"))?.length ?? 0;
      const close = html.match(new RegExp(`</${tag}>`, "g"))?.length ?? 0;
      assert.equal(open, close, `<${tag}> balanced`);
    }
  });
}

for (const [name, spec] of Object.entries(LINKS)) {
  test(`${name}: token_hash link to KAIDLY /auth/confirm with a valid type and next`, () => {
    const html = read(name);
    const expected = `{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&amp;type=${spec.type}&amp;next=${spec.next}`;
    const hrefs = [...html.matchAll(/href="([^"]+)"/g)].map((m) => m[1]).filter((h) => h !== "https://kaidly.ee");
    assert.deepEqual(new Set(hrefs), new Set([expected]), "button and plain fallback use the same link");
    assert.equal(hrefs.length, 6, "button + fallback per language");
    assert.equal(html.split(`>${expected}</a>`).length - 1, 3, "visible fallback URL");
    assert.match(html, /word-break:break-all;"><a href/, "fallback URL wraps on narrow screens");
    assert.ok(ROUTE_TYPES.includes(spec.type));
    assert.ok(isAllowedRedirectPath(spec.next));
  });
}

test("email_change shows the new address and keeps its variables", () => {
  const html = read("email_change");
  assert.equal(html.match(/\{\{ \.NewEmail \}\}/g)?.length, 3);
  assert.ok(html.includes("{{ .TokenHash }}") && html.includes("{{ .SiteURL }}"));
});

test("reauthentication: one-time code, no link", () => {
  const html = read("reauthentication");
  assert.equal(html.match(/\{\{ \.Token \}\}/g)?.length, 3);
  assert.doesNotMatch(html, /TokenHash|\/auth\/confirm/);
  assert.match(templateSubject("reauthentication"), /\{\{ \.Token \}\}/);
  assert.equal([...html.matchAll(/href="([^"]+)"/g)].filter((m) => m[1] !== "https://kaidly.ee").length, 0);
});

test("security notifications: no tokens; changed-address mail names both addresses", () => {
  for (const name of REQUIRED.filter((n) => n.endsWith("_notification"))) {
    const html = read(name);
    assert.doesNotMatch(html, /\.Token|\.TokenHash/, name);
    for (const [, href] of html.matchAll(/href="([^"]+)"/g)) assert.ok(href === "https://kaidly.ee" || href === "{{ .SiteURL }}/auth/forgot-password", `${name}: ${href}`);
  }
  const changed = read("email_changed_notification");
  assert.ok(changed.includes("{{ .OldEmail }}") && changed.includes("{{ .Email }}"));
});

test("only the features KAIDLY uses are active; unused notifications stay disabled", () => {
  const active = Object.entries(ALL).filter(([, t]) => t.active).map(([n]) => n).sort();
  assert.deepEqual(active, ["confirmation", "email_change", "email_changed_notification", "password_changed_notification", "recovery"]);
  assert.ok(existsSync(repo("docs/EMAIL_TEMPLATES.md")));
});

test("previews use fake values and leave no placeholder", () => {
  for (const name of REQUIRED) for (const lang of LANGS) {
    const html = preview(name, lang) as string;
    assert.doesNotMatch(html, /\{\{/);
    assert.match(html, new RegExp(`<html lang="${lang}">`));
    assert.doesNotMatch(html, /@(?!example\.invalid)[a-z0-9-]+\.[a-z]{2,}/i, "only example.invalid addresses");
  }
});

// ---------------------------------------------------------------------------
// Deadline reminder e-mail (application, docs/EMAIL_NOTIFICATIONS.md)
// ---------------------------------------------------------------------------

test("deadline reminder: the migration stores exactly the generated templates", () => {
  const migration = readFileSync(repo("supabase/migrations/20261006100000_email_reminders.sql"), "utf8");
  assert.ok(migration.includes(appTemplatesSql()), "run node scripts/email-templates.mjs --sql and update the migration");
});

test("deadline reminder: generic text in ET/EN/RU, notification-centre link, no data placeholders", () => {
  const expected = {
    et: ["KAIDLY | Sul on uus tähtajaga seotud teavitus", "Sul on uus teavitus", "Vaata teavitusi"],
    en: ["KAIDLY | You have a new deadline notification", "You have a new notification", "View notifications"],
    ru: ["KAIDLY | У вас новое уведомление о сроке", "У вас новое уведомление", "Открыть уведомления"],
  } as const;
  for (const lang of LANGS as ("et" | "en" | "ru")[]) {
    const mail = appEmail("deadline_reminder", lang) as { subject: string; html: string; text: string };
    const [subject, heading, cta] = expected[lang];
    assert.equal(mail.subject, subject);
    for (const part of [mail.html, mail.text]) {
      assert.ok(part.includes(heading) && part.includes(cta), lang);
      assert.ok(part.includes("{{site_url}}/teavitused"), "CTA: the notification centre");
      assert.ok(part.includes("{{site_url}}/konto#teavitused"), "settings link");
      // The only placeholder; nothing else could carry data into the mail.
      assert.deepEqual([...new Set(part.match(/\{\{[^}]*\}\}/g))], ["{{site_url}}"]);
      assert.doesNotMatch(part, /utm_|track|pixel|unsubscribe|<img\b|<svg\b|data:|background-image/i);
    }
    assert.match(mail.html, new RegExp(`<html lang="${lang}">`));
    assert.match(mail.html, /max-width:560px/);
    assert.ok(mail.html.includes("Elektripaigaldise käit. Lihtsalt.") || lang !== "et");
  }
});

test("deadline reminder privacy: operational values cannot reach the e-mail", () => {
  // The renderer takes no data at all; this pins that a future change cannot start
  // passing notification fields through (the database test checks the real request too).
  const sensitive = ["Secret Factory", "Main Switchboard PK-01", "Annual inspection", "12.10.2026", "2026-10-12", "Critical deficiency"];
  const render = appEmail as unknown as (name: string, lang: string, fixture?: unknown) => { subject: string; html: string; text: string };
  for (const lang of LANGS) {
    const mail = render("deadline_reminder", lang, { company: sensitive[0], installation: sensitive[1], activity: sensitive[2], due: sensitive[3], deficiency: sensitive[5] });
    for (const value of sensitive) for (const part of [mail.subject, mail.html, mail.text]) assert.ok(!part.includes(value), `${lang}: ${value}`);
  }
  assert.equal(appEmail.length, 2, "appEmail(name, lang) — no data parameter");
});
